### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by samanthatarrice** [samanthatarrice/wwcode-hackathon2023#6]

**Comment by yuhwaa** [comment]
I am working on this. Please assign the issue to me.

**Comment by yuhwaa** [comment]
<img width="437" alt="Screenshot 2023-10-16 at 8 48 26 PM" src="https://github.com/samanthatarrice/wwcode-hackathon2023/assets/101489014/5f958523-4345-437a-8d9c-455059aa562b">

A workable logo I've come up with; below are some sketches I had but I am having a hard time converting them digitally as well as finding vector files to make them happen.

**Comment by yuhwaa** [comment]
<img width="944" alt="Screenshot 2023-10-17 at 12 19 14 PM" src="https://github.com/samanthatarrice/wwcode-hackathon2023/assets/101489014/924c05a6-9003-442f-8e83-aa63fae3b4ba">

**Comment by yuhwaa** [comment]
<img width="367" alt="Screenshot 2023-10-21 at 7 13 46 PM" src="https://github.com/samanthatarrice/wwcode-hackathon2023/assets/101489014/a266d0e2-0859-469d-b8c6-76ea049abfbb">
